### PR TITLE
use 

### PR DESCRIPTION
**Pull request by edewit**
fixing issue [RHMAP-7031](https://issues.jboss.org/browse/RHMAP-7031)

### CODE REVIEW

**Comment by secondsun** [comment]
@edewit Is building the app in studio sufficient to verify?

**Comment by jcesarmobile** [comment]
bootstrap js was updated to 3.3.6, but the bootstrap.css is the 3.0.3 version

**Comment by jcesarmobile** [comment]
My previous comment has not been addressed

**Comment by jcesarmobile** [comment]
I have updated bootstrap and now it looks good to me, but as I was the one who made latest changes I would like someone else to review before merging. @corinnekrych @secondsun 

It can't be tested on studio right now, what I did to test was to pick the PR changes and put them on an existing local app

**Comment by corinnekrych** [comment]
+1

**Pull request merged**
