### PR TITLE
Add licenses folder

### PR DESCRIPTION
**Pull request by dimitraz**

### CODE REVIEW

**Comment by dimitraz** [comment]
ping @lgriffin 
not sure whether or not to manually add in other local licenses that were not automatically generated

**Comment by lgriffin** [comment]
If it was not automatically generated don't sweat it:
No local license could be found for the dependency is the line that goes in. That is perfectly fine and we can do that even when manually doing other licenses that are non package.json. So don't worry about adding it in, the remote license is our backup there

@ciaranRoche just as an FYI

**Comment by dimitraz** [comment]
@lgriffin ok, thanks Leigh. Going to update this and other PRs because I haven't been using the `--full-dependency-tree` flag

**Comment by dimitraz** [comment]
@lgriffin updated

**Comment by lgriffin** [comment]
Perfect if I merged any just issue a new PR

**Pull request merged**
